-- This file used to hold hand-written demo data. It was out of date (it used a role that no longer
-- exists and bypassed the FIFO lot model), so it has been replaced by this note on purpose.
--
-- Demo data now lives in Flyway migrations that only the demo setup loads:
--   src/main/resources/db/demo/   users (admin, warehouse, staff), suppliers, products, lots, movements
-- The `local` Spring profile and docker-compose.yml add that folder to the Flyway locations.
-- A production deployment uses src/main/resources/db/migration only and has no seeded accounts.
--
-- Do not run INSERT statements against the stock tables by hand: product.stock must always equal the
-- sum of the remaining quantities of its lots, and only the application keeps that invariant.
SELECT 1;
